# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-30 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170730_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculation',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.RenameField(
            model_name='matriculation',
            old_name='class_couse',
            new_name='class_course',
        ),
    ]
