# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Alternativas',
                'verbose_name': 'Alternativa',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True)),
                ('option_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Alternative')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
            options={
                'verbose_name_plural': 'Respostas',
                'verbose_name': 'Resposta',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type_evaluated', models.PositiveIntegerField(choices=[(1, 'Docente'), (2, 'Coordenador'), (3, 'Curso'), (4, 'Polo')])),
                ('need_identify', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Formulários',
                'verbose_name': 'Formulário',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type_question', models.PositiveIntegerField(choices=[(1, 'Texto Curto'), (2, 'Texto Longo'), (3, 'Escolha Única'), (4, 'Escolha Múltipla'), (5, 'Escala'), (6, 'Concordo ou Discordo')])),
                ('is_required', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form')),
                ('related_alternative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_alternative', to='forms.Alternative')),
            ],
            options={
                'verbose_name_plural': 'Questões',
                'verbose_name': 'Questão',
            },
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Question'),
        ),
    ]
