# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alternativas',
                'verbose_name': 'Alternativa',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True)),
                ('scale', models.PositiveIntegerField(null=True)),
                ('dont_apply', models.BooleanField(default=False, verbose_name='Não se aplica')),
                ('yes_no', models.PositiveIntegerField(blank=True, choices=[(1, 'Concordo/Sim'), (2, 'Concordo parcialmente/Parcialmente'), (3, 'Discordo/Não')], null=True)),
            ],
            options={
                'verbose_name_plural': 'Respostas',
                'verbose_name': 'Resposta',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Alternative')),
            ],
            options={
                'verbose_name_plural': 'Alternativa selecionada',
                'verbose_name': 'Alternativa selecionada',
            },
        ),
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluated', models.PositiveIntegerField(choices=[(1, 'Docente'), (2, 'Coordenador'), (3, 'Curso'), (4, 'Polo')], verbose_name='Tipo de Avaliado')),
                ('login_required', models.BooleanField(default=False, verbose_name='Login é obrigatório?')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('access_code', models.CharField(max_length=64, unique=True, verbose_name='código de acesso')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Aberto'), (2, 'Fechado')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Formulários Aplicados',
                'verbose_name': 'Formulário Aplicado',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Formulários',
                'verbose_name': 'Formulário',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type_question', models.PositiveIntegerField(choices=[(1, 'Texto Curto'), (2, 'Texto Longo'), (3, 'Escolha Única'), (4, 'Escolha Múltipla'), (5, 'Escala'), (6, 'Concordo ou Discordo')])),
                ('is_required', models.BooleanField(default=True)),
                ('max_size', models.PositiveIntegerField(null=True, verbose_name='Tamanho máximo da resposta')),
                ('max_scale', models.PositiveIntegerField(null=True, verbose_name='Escala máxima da resposta')),
                ('show_yes_no', models.BooleanField(default=False, verbose_name='Mostrar Sim ou Não')),
                ('left_label', models.CharField(max_length=50, verbose_name='Label esquerdo')),
                ('middle_label', models.CharField(max_length=50, verbose_name='Label central')),
                ('right_label', models.CharField(max_length=50, verbose_name='Label direito')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form')),
                ('related_alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_alternative', to='forms.Alternative')),
            ],
            options={
                'verbose_name_plural': 'Questões',
                'verbose_name': 'Questão',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('apply_form', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.ApplyForm')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
            options={
                'verbose_name_plural': 'Respostas Central',
                'verbose_name': 'Resposta Central',
            },
        ),
        migrations.AddField(
            model_name='applyform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Question'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Response'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Response'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Question'),
        ),
    ]
