# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='form',
            name='need_identify',
            field=models.BooleanField(default=True, verbose_name='Precisa de Identificação?'),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='form',
            name='type_evaluated',
            field=models.PositiveIntegerField(choices=[(1, 'Docente'), (2, 'Coordenador'), (3, 'Curso'), (4, 'Polo')], verbose_name='Tipo de Avaliado'),
        ),
    ]
