# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20161228_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='related_alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_alternative', to='forms.Alternative'),
        ),
    ]
