# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20170522_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='scale',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
