# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_answer_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='left_label',
            field=models.CharField(default='', max_length=50, verbose_name='Label esquerdo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='max_scale',
            field=models.PositiveIntegerField(null=True, verbose_name='Escala máxima da resposta'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_size',
            field=models.PositiveIntegerField(null=True, verbose_name='Tamanho máximo da resposta'),
        ),
        migrations.AddField(
            model_name='question',
            name='middle_label',
            field=models.CharField(default='', max_length=50, verbose_name='Label central'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='right_label',
            field=models.CharField(default='', max_length=50, verbose_name='Label direito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='show_yes_no',
            field=models.BooleanField(default=False, verbose_name='Mostrar Sim ou Não'),
        ),
    ]
