# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20170726_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Aberto'), (2, 'Fechado')], default=1),
        ),
    ]
