# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-28 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pole_name'),
        ('forms', '0011_auto_20170727_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Alternative')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Question')),
            ],
            options={
                'verbose_name_plural': 'Alternativa selecionada',
                'verbose_name': 'Alternativa selecionada',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
            options={
                'verbose_name_plural': 'Respostas',
                'verbose_name': 'Resposta',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='person',
        ),
        migrations.AddField(
            model_name='answeroption',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Response'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Response'),
        ),
    ]
