# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20170728_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Resposta Central', 'verbose_name_plural': 'Respostas Central'},
        ),
        migrations.AddField(
            model_name='apllyform',
            name='access_code',
            field=models.CharField(default=None, max_length=64, unique=True, verbose_name='código de acesso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apllyform',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
