# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20170729_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApllyForm',
            new_name='ApplyForm',
        ),
    ]
