# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20170729_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='applyForm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.ApplyForm'),
        ),
    ]
