# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_response_applyform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='applyForm',
            new_name='apply_form',
        ),
    ]
