# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20170729_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyform',
            options={'verbose_name': 'Formulário Aplicado', 'verbose_name_plural': 'Formulários Aplicados'},
        ),
        migrations.RemoveField(
            model_name='form',
            name='status',
        ),
        migrations.AddField(
            model_name='applyform',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Aberto'), (2, 'Fechado')], default=1),
        ),
    ]
